name: AppMedia
favicon: null
layout_spectrum: 0.2845149
typography_spectrum: 0.1114739
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#6798FE'
    - '#0084FF'
    - '#14243D'
    - '#CE8B6E'
  brandStrength: 0.6926306
  lightness: 0.3125
  saturation: 0.1807228
  rhythmicContrast: 0.2564884
purpose: []
