typography_spectrum: 0.53885
color:
  brandColors:
    - '#FFFFFF'
    - '#6798FE'
    - '#0084FF'
    - '#14243D'
    - '#CE8B6E'
  brandStrength: 0.4375
  lightness: 0.0625
  saturation: 0.75
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2845149
analytics:
  google: null
  facebook: null
  twitter: null
name: AppMedia
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Apploggen
purpose: []
